// Generated by CoffeeScript 1.3.3
var app;

app = {
  changeUrl: false,
  changeTitle: true,
  checkPath: function() {
    var el, token;
    token = window.location.pathname.replace(/\//g, '');
    el = $('.available a[rel="' + token + '"]');
    if (el) {
      return el.click();
    }
  }
};

$(function() {
  var History;
  History = window.History;
  if (typeof console !== "undefined") {
    window.console = {
      log: function() {
        var argument, output, _i, _len, _results;
        output = $('#output');
        output.text("");
        _results = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          argument = arguments[_i];
          if (output.text().length) {
            output.append(', ');
          }
          _results.push(output.append(argument));
        }
        return _results;
      }
    };
  }
  $('.clickable').live('click', function(e) {
    var data, template, that;
    that = $(this);
    e.preventDefault();
    that.siblings().removeClass('selected');
    that.addClass('selected');
    template = $('.template-' + that.attr('rel')).html();
    data = {
      title: that.text(),
      github: that.attr('href'),
      project: that.attr('href').split('/')[4]
    };
    $('#playground').html(Mustache.render(template, data));
    prettyPrint();
    if (app.changeTitle) {
      $('title').text(data.title);
    }
    if (History.enabled && app.changeUrl) {
      History.pushState({}, data.title, "/" + that.attr('rel') + "/");
    }
    return app.changeUrl = true;
  });
  $('#run').live('click', function() {
    var code;
    try {
      code = $(this).prev().text();
      if ($('.available a.selected').attr('rel') === 'coffeescript') {
        code = CoffeeScript.compile(code);
      }
      return eval(code);
    } catch (e) {
      return $('#output').text('<error> ' + e);
    }
  });
  app.checkPath();
  History.Adapter.bind(window, 'statechange', function() {
    return app.checkPath();
  });
  if (!window.location.pathname.replace(/\//g, '')) {
    app.changeTitle = false;
    return $('.clickable').first().click();
  }
});
